add_newline = false
format = """
[┌─](bold red)$directory$git_branch$git_status$nodejs$python$rust$cmd_duration
[└─➜](bold red) """

[directory]
style = "bold red"
truncation_length = 3
truncate_to_repo = true

[git_branch]
symbol = " "
style = "bold red"
format = "[$symbol$branch]($style) "

[git_status]
style = "bold red"
format = "([$all_status$ahead_behind]($style) )"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
modified = "!${count}"
untracked = "?${count}"
staged = "+${count}"
deleted = "✘${count}"

[nodejs]
symbol = " "
style = "bold red"
format = "[$symbol$version]($style) "

[python]
symbol = " "
style = "bold red"
format = "[$symbol$version]($style) "

[rust]
symbol = " "
style = "bold red"
format = "[$symbol$version]($style) "

[cmd_duration]
style = "bold red"
format = "[  ${duration}]($style) "
min_time = 2000

[character]
success_symbol = "[➜](bold red)"
error_symbol = "[✗](bold red)"
