#========== CYBERPUNK RED FORZADO ==========

# General
update_ms = 800
preset = 1
truecolor = true
force_tty = false
lowcolor = false
theme_background = true
background = false

# TEMA (FORZADO)
color_theme = "cyber-punk"

# Visualización
graph_symbol = "braille"
graph_symbol_cpu = "braille"
graph_symbol_mem = "braille"
graph_symbol_net = "braille"
graph_symbol_proc = "braille"
graph_gradient = 1
graph_gradient_fill = true

# CPU
proc_per_core = true
cpu_graph_upper = "CPU Total"
cpu_graph_lower = "CPU Cores"
cpu_sensor = "Auto"

# Memoria
show_swap = true
show_disks = true
mem_graph_upper = "RAM"
mem_graph_lower = "Swap"

# Red
net_auto = true
net_speed_bits = false
net_graph_upper = "Download"
net_graph_lower = "Upload"

# GPU
check_gpu = true
gpu_driver = true
gpu_graph_upper = "GPU"
gpu_graph_lower = "VRAM"

# Procesos
proc_sorting = "cpu"
proc_reversed = true
proc_tree = false
proc_colors = true
proc_gradient = true
proc_cpu_graphs = true
proc_gpu = true
proc_show_cmd = false

# Sistema
show_uptime = true
show_battery = true
show_battery_percent = true
temp_celsius = true

# Discos
disks_filter = "/,/home"
