# ============================================
# ATEJOS DE TECLADO
# ============================================

# Variables
$mod = SUPER

# ------------------- Sistema -------------------
bind = $mod, M, exit
bind = $mod, W, togglefloating
bind = $mod, Q, killactive
bind = $mod, F, fullscreen

# ------------------- Lanzadores -------------------
bind = $mod, RETURN, exec, alacritty
bind = $mod, D, exec, wofi --show drun

# ------------------- Workspaces -------------------
bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5
bind = $mod, 6, workspace, 6
bind = $mod, 7, workspace, 7

bind = $mod, RIGHT, workspace, e+1
bind = $mod, LEFT, workspace, e-1

# ------------------- Movimiento de ventanas -------------------
bindm = $mod, mouse:272, movewindow
bindm = $mod, mouse:273, resizewindow

# ------------------- Lanzadores (otros) -------------------
bind = ALT, TAB, exec, ~/.config/hypr/alt-tab.sh

# ------------------- Multimedia -------------------
# Volumen
bind = , XF86AudioRaiseVolume, exec, pamixer -i 5
bind = , XF86AudioLowerVolume, exec, pamixer -d 5
bind = , XF86AudioMute, exec, pamixer -t

# Brillo
bind = , XF86MonBrightnessUp, exec, brightnessctl set +5%
bind = , XF86MonBrightnessDown, exec, brightnessctl set 5%-

# ------------------- Screenshots -------------------
bind = $mod, P, exec, grim -g "$(slurp)" - | wl-copy
