# ============================================
# ARCHIVO PRINCIPAL DE HYPRLAND
# ============================================

# Importar configuraciones modulares
source = ~/.config/hypr/env.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/binds.conf
source = ~/.config/hypr/windows-rules.conf

# Ejecutar scripts al inicio
exec-once = ~/.config/hypr/startup.sh
exec-once = ~/.config/waybar/scripts/bluetooth-scan-daemon.sh

# Configuración general
general {
    gaps_in = 5
    gaps_out = 20
    border_size = 2
    col.active_border = rgba(ff3333ff)
    col.inactive_border = rgba(ff3333ff)
    layout = dwindle
}

input {
    kb_layout = us
    follow_mouse = 1
    touchpad {
        natural_scroll = false
    }
}

decoration {
    blur {
        enabled = true
        size = 8
        passes = 3
        new_optimizations = true
    }
}

